version: 2

models:

    - name: sales
      description: products name 
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: number of frequency in  ordering
            tests : 
            - not_null 

          - name: products_id
            description: number of frequency
            tests : 
            - not_null

          - name: qty

          - name: turnover
            description: sum of all turnover
            tests : 
            - not_null
            
          - name: purchase_cost
            description: sum of all cost minus sales cost 
            tests : 
            - not_null
            
          - name: margin